apiVersion: v1
kind: Service
metadata:
  name: {{ include "troll.fullname" . }}
  labels:
    {{- include "troll.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '5040'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "troll.selectorLabels" . | nindent 4 }}
